apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deployment-test-app-frontend
  namespace: storefront-dev
  annotations:
    "kubernetes.io/ingress.class": "alb"
    "alb.ingress.kubernetes.io/scheme": "internet-facing"
    "alb.ingress.kubernetes.io/target-type": "ip"
    "alb.ingress.kubernetes.io/listen-ports": "[{\"HTTP\": 80}]"
    "alb.ingress.kubernetes.io/healthcheck-path": "/"
    "alb.ingress.kubernetes.io/group.name": "deployment-test-app-dev"
  labels:
    app.kubernetes.io/name: deployment-test-app-frontend
    app.kubernetes.io/managed-by: deepagent
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deployment-test-app-frontend
                port:
                  number: 80
